-- liquibase formatted sql

-- changeset bikkul:1
CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(32) NOT NULL,
    second_name VARCHAR(32) NOT NULL,
    email VARCHAR(64) NOT NULL UNIQUE,
    login VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(20) NOT NULL,
    birthday TIMESTAMP WITHOUT TIME ZONE NOT NULL
);