version: '3.1'

services:
  mwb-user-service:
    build: ./mwb-user-service
    image: mwb-user-service-image
    container_name: user-service
    ports:
      - "9090:9090"
    depends_on:
      - user-service-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/mwb-users
      - SPRING_DATASOURCE_USER=user
      - SPRING_DATASOURCE_PASSWORD=user

  mwb-users-db:
    image: postgres:14-alpine
    container_name: mwb-users-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=mwb-users
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user

  mwb-wallet-service:
    build: ./mwb-wallet-service
    image: mwb-wallet-service-image
    container_name: wallet-service
    ports:
      - "8080:8080"
    depends_on:
      - mwb-wallet-db
      - user-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/mwb-wallets
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root
      - USER-SERVICE_URL=http://user-service:9090

  mwb-wallet-db:
    image: postgres:14-alpine
    container_name: mwb-wallet-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=mwb-wallets
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
