server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:mem:users
    username: test
    password: test
    driver-class-name: org.h2.Driver

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml

#  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USER}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace